// This file is auto-generated by the Ziggy package
// See https://github.com/tighten/ziggy

// Initialize with empty routes that will be replaced by server-side @routes
export const Ziggy = {
    url: window.location.origin,
    port: null,
    defaults: {},
    routes: {}
};
