export const COUNTRIES = [
  { value: 'sa', label: 'Saudi Arabia' },
  { value: 'ae', label: 'United Arab Emirates' },
  { value: 'qa', label: 'Qatar' },
  { value: 'kw', label: 'Kuwait' },
  { value: 'bh', label: 'Bahrain' },
  { value: 'om', label: 'Oman' },
  { value: 'eg', label: 'Egypt' },
  { value: 'jo', label: 'Jordan' },
  { value: 'lb', label: 'Lebanon' },
  { value: 'sy', label: 'Syria' },
  { value: 'iq', label: 'Iraq' },
  { value: 'ye', label: 'Yemen' },
  { value: 'pk', label: 'Pakistan' },
  { value: 'in', label: 'India' },
  { value: 'ph', label: 'Philippines' },
  { value: 'id', label: 'Indonesia' },
  { value: 'my', label: 'Malaysia' },
  { value: 'sg', label: 'Singapore' },
  { value: 'th', label: 'Thailand' },
  { value: 'vn', label: 'Vietnam' },
  { value: 'mm', label: 'Myanmar' },
  { value: 'kh', label: 'Cambodia' },
  { value: 'la', label: 'Laos' },
  { value: 'bn', label: 'Brunei' },
  { value: 'tl', label: 'Timor-Leste' },
  { value: 'np', label: 'Nepal' },
  { value: 'bd', label: 'Bangladesh' },
  { value: 'lk', label: 'Sri Lanka' },
  { value: 'mv', label: 'Maldives' },
  { value: 'bt', label: 'Bhutan' },
];

export const EMPLOYEE_ROLES = [
  { value: 'admin', label: 'Admin' },
  { value: 'manager', label: 'Manager' },
  { value: 'foreman', label: 'Foreman' },
  { value: 'workshop', label: 'Workshop' },
  { value: 'employee', label: 'Employee' },
];

export const EMPLOYEE_STATUS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
  { value: 'on_leave', label: 'On Leave' },
]; 